### ISSUE TITLE
cli: Replace table logic with an external library

### ISSUE THREAD

**Issue by BrunoRosendo** [reanahub/reana-client-go#43]
Table data is and will be strongly present in the client. Currently, this logic is being handled manually with slices. It would be good to use an external library (maybe dataframes or something like [tablib](https://tablib.readthedocs.io/en/stable/))

Replace any existing code that can be improved by this

**Comment by BrunoRosendo** [comment]
This was the best library I could find for this purpose:
https://github.com/go-gota/gota

**Comment by BrunoRosendo** [comment]
After experimenting a bit with gota, I had some problems with it:
- The logic is column based, while in here we have a row based logic. For example, the library has a lot more support to add columns than rows. There isn't even a built in function to append rows.
- I couldn't find an easy way to store columns with multiple types. There are situations where we mix strings and ints, for examples.

That said, I found a second library which might work better for us: https://github.com/rocketlaunchr/dataframe-go
It's still column based, but we can define a capacity at the start, initialize mixed type columns with just the headers, and then append the rows. I think it's easier to convert our data with this one

**Comment by mdonadoni** [comment]
> I couldn't find an easy way to store columns with multiple types. There are situations where we mix strings and ints, for example.

Are there any cases where we need mixed types other than when we convert `None` to `"-"`? This is important to know because, in general, sorting can only happen between values of the same type.

**Comment by BrunoRosendo** [comment]
Other than that, I think it's just that case where the size is a string if human readable or an int if not. But that means the whole column changes type so it's not a problem.
Thinking a bit more about it, if there's a nice way to treat the "-" with null values then the lack of mixed types shouldn't be a problem either
