### ISSUE TITLE
cli: investigate `list` command performance

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client-go#63]
In the old initial golang tests, the `list` command was faster in Go than in Python, about 6-10 times, depending on how much workflow runs the user had.

Recently, due to some changes, the Go implementation became much slower, even slower than the Python implementation, when working with about 800 workflows from a remote REANA cluster over a fast network:

```console
$ hyperfine --warmup 5 'reana-client list --size 20' './reana-client-go list --size 20'
Benchmark 1: reana-client list --size 20
  Time (mean ± σ):     620.2 ms ±  16.4 ms    [User: 445.6 ms, System: 41.1 ms]
  Range (min … max):   601.8 ms … 659.0 ms    10 runs

Benchmark 2: ./reana-client-go list --size 20
  Time (mean ± σ):     805.4 ms ±  79.1 ms    [User: 6.3 ms, System: 6.5 ms]
  Range (min … max):   723.5 ms … 943.3 ms    10 runs

Summary
  'reana-client list --size 20' ran
    1.30 ± 0.13 times faster than './reana-client-go list --size 20'
```

The difference is even more obvious without pagination:

```console
$ hyperfine --warmup 2 'reana-client list' './reana-client-go list'
Benchmark 1: reana-client list
  Time (mean ± σ):      1.307 s ±  0.108 s    [User: 0.513 s, System: 0.041 s]
  Range (min … max):    1.194 s …  1.532 s    10 runs

Benchmark 2: ./reana-client-go list
  Time (mean ± σ):     26.190 s ±  1.561 s    [User: 0.045 s, System: 0.028 s]
  Range (min … max):   24.112 s … 28.542 s    10 runs

Summary
  'reana-client list' ran
   20.05 ± 2.04 times faster than './reana-client-go list'
```

We should do two things:

1. Investigate the root cause and eliminate the slowness of the Go client implementation to make it fast again.
2. We might perhaps take advantage of this occasion and introduce a new `--profile` CLI option to all the `reana-client-go` commands that would generate a nice CPU profile enabling to see where the run time is most spent, see e.g. the good old [profiling tutorial](https://go.dev/blog/pprof). Such a generic `--profile` option would come handy in the future should we need to help users investigate their performance.

**Comment by audrium** [comment]
Compared to [update list command to use swagger api client ](https://github.com/reanahub/reana-client-go/commit/9dcc1120fb487c48d2216c4a9807b8da2e0946ee) commit our client got 10 times slower:
```
hyperfine --warmup 2 './reana-client-go-swagger list' './reana-client-go list'
Benchmark 1: ./reana-client-go-swagger list
  Time (mean ± σ):     606.2 ms ±  66.7 ms    [User: 17.1 ms, System: 5.5 ms]
  Range (min … max):   501.2 ms … 706.9 ms    10 runs

Benchmark 2: ./reana-client-go list
  Time (mean ± σ):      6.063 s ±  0.212 s    [User: 0.043 s, System: 0.012 s]
  Range (min … max):    5.798 s …  6.445 s    10 runs

Summary
  './reana-client-go-swagger list' ran
   10.00 ± 1.15 times faster than './reana-client-go list'
```

Back then it was 2.5 times faster compared to the Python client:
```
hyperfine --warmup 2 './reana-client-go-swagger list' 'reana-client list'
Benchmark 1: ./reana-client-go-swagger list
  Time (mean ± σ):     603.2 ms ±  26.6 ms    [User: 20.6 ms, System: 5.7 ms]
  Range (min … max):   545.5 ms … 643.3 ms    10 runs

Benchmark 2: reana-client list
  Time (mean ± σ):      1.567 s ±  0.057 s    [User: 0.929 s, System: 0.049 s]
  Range (min … max):    1.465 s …  1.677 s    10 runs

Summary
  './reana-client-go-swagger list' ran
    2.60 ± 0.15 times faster than 'reana-client list'
```

After checking various commits I found that performance dropped significantly after [this commit (implement more flags in the list command)](https://github.com/reanahub/reana-client-go/commit/c41d3a6fc7267e2b053fe05004bf8941403a7fb9). Compared to the swagger commit it became almost 10 times slower:

```
hyperfine --warmup 2 './reana-client-go-swagger list' './reana-client-go-flags list'
Benchmark 1: ./reana-client-go-swagger list
  Time (mean ± σ):     644.7 ms ±  92.8 ms    [User: 15.6 ms, System: 10.6 ms]
  Range (min … max):   558.9 ms … 892.5 ms    10 runs

Benchmark 2: ./reana-client-go-flags list
  Time (mean ± σ):      6.051 s ±  0.190 s    [User: 0.046 s, System: 0.013 s]
  Range (min … max):    5.810 s …  6.397 s    10 runs

Summary
  './reana-client-go-swagger list' ran
    9.39 ± 1.38 times faster than './reana-client-go-flags list'
```


Tested with:
```
reana-client list | wc -l
1210
```

**Comment by mdonadoni** [comment]
The issue is caused by https://github.com/reanahub/reana-workflow-controller/issues/464.

In particular, the Go client always adds the query parameters `include_progress`, `include_workspace_size` and `include_retention_rules` to the request, with false as a default value, even when the corresponding flags are not specified by the user when invoking `reana-client-go`. Due to an issue in `reana-workflow-controller`, these flags were not correctly parsed as being `False`, resulting in a longer lasting request.

We should:
  - Fix the parsing of the parameters in `reana-workflow-controller` (done in https://github.com/reanahub/reana-workflow-controller/pull/465)
  - Change the Go client so that it adds these parameters only when they are specified by the user. This is needed because if the user only specifies `--verbose`, the response from the server would not be complete given that `include_progress`, `include_workspace_size` and `include_retention_rules` would be set to false and would override the `verbose` flag.
