### ISSUE TITLE
cli: implement `delete` functionality

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client-go#93]
```console
$ reana-client delete --help
Usage: reana-client delete [OPTIONS]

  Delete a workflow.

  The ``delete`` command removes workflow run(s) from the database. Note that
  the workspace will always be deleted, even when ``--include-workspace`` is
  not specified. Note also that you can remove all past runs of a workflow by
  specifying ``--include-all-runs`` flag.

  Example:

       $ reana-client delete -w myanalysis.42

       $ reana-client delete -w myanalysis.42 --include-all-runs

Options:
  --include-all-runs       Delete all runs of a given workflow.
  --include-workspace      Delete workspace from REANA.
  -w, --workflow TEXT      Name or UUID of the workflow. Overrides value of
                           REANA_WORKON environment variable.
  -t, --access-token TEXT  Access token of the current user.
  --help                   Show this message and exit.
```

**Comment by tiborsimko** [comment]
Beware that `--include-workspace` is always on. It is a backwards-compatible option, so we keep it in the client, but it does not have any effect. We always delete workspace when deleting workflow now.

**Comment by BrunoRosendo** [comment]
> Beware that `--include-workspace` is always on. It is a backwards-compatible option, so we keep it in the client, but it does not have any effect. We always delete workspace when deleting workflow now.

@tiborsimko Should the client always pass the flag as `True` or does the server already have this behavior?

**Comment by tiborsimko** [comment]
> Should the client always pass the flag as True or does the server already have this behavior?

On the server we still have the flag on false in places:

```python
def delete_workflow(workflow, all_runs=False, workspace=False):
```

It would be best to force it in the client anyway, in this way the new behaviour would work against any remote REANA cluster out there, be it old or new.
